const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const path = require('path');
const source = fs.readFileSync(path.join(__dirname, '..', 'modules/dashboard-hub/dashboard-insight-dedup.js'), 'utf8');
const sandbox = { console: { warn() {}, error() {} }, setTimeout(fn) { fn(); return 1; }, clearTimeout() {}, requestAnimationFrame(fn) { fn(); }, window: {} };
vm.runInNewContext(source, sandbox);
const D = sandbox.window.DashboardInsightDedup;
assert.ok(D);
assert.strictEqual(D._norm('  Ringkasan Harian Finance & Vehicle  A   B '), 'a b');
assert.strictEqual(D._norm('Rekomendasi utk Anda: Batasi makan'), 'batasi makan');
assert.strictEqual(D._similarity('Batasi makan dan evaluasi budget', 'Batasi makan; evaluasi budget'), 1);
assert.ok(D._similarity('Budget makan naik 20 persen', 'Budget makan naik 20%') < 0.94);
assert.ok(D._similarity('Budget makan naik', 'Harga bensin naik') < 0.94);
assert.ok(D._tokens('dan yang untuk budget makan').has('budget'));
const build = fs.readFileSync(path.join(__dirname, '..', 'scripts/build.js'), 'utf8');
assert.ok(build.includes('modules/dashboard-hub/dashboard-insight-dedup.js'));
const bundle = fs.readFileSync(path.join(__dirname, '..', 'app-bundle-b.min.js'), 'utf8');
assert.ok(bundle.includes('DashboardInsightDedup'));
assert.ok(bundle.includes('SIMILARITY_THRESHOLD'));
assert.ok(bundle.includes('MutationObserver'));
console.log('dashboard-insight-dedup: 9/9 PASS');
