const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const b=fs.readFileSync(path.join(root,'app-bundle-b.min.js'),'utf8');
const a=fs.readFileSync(path.join(root,'app-bundle-a.min.js'),'utf8');
const ext=fs.readFileSync(path.join(root,'modules/vehicle/part-crud-s2041.js'),'utf8');
function ok(x,m){if(!x)throw new Error(m)}
ok(b.includes('applyStockPurchase'),'purchase stock ledger missing');
ok(b.includes('replaceStockUsages'),'service usage reconciliation missing');
ok(b.includes('revertStockUsage'),'service usage rollback missing');
ok(a.includes('stockModal'),'stock modal contract missing');
ok(ext.includes('stockServiceComponentId'),'component SOT editor missing');
ok(ext.includes('stockOemCode'),'OEM editor missing');
ok(ext.includes('adjustmentHistory'),'manual quantity adjustment ledger missing');
ok(ext.includes('manual-delete-with-history'),'safe archive delete missing');
ok(ext.includes('window.PartPickerS2041'),'canonical PartPicker API missing');
ok(ext.includes('data-part-picker'),'generic PartPicker opt-in missing');
ok(ext.includes("selectId+'_addPart'") && ext.includes("injectPicker('servisPartId'"),'service add-part entry point missing');
ok(ext.includes("injectPicker('txStockItem'"),'purchase add-part entry point missing');
ok(ext.includes('serviceComponentId'),'component relationship missing');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const prod=fs.readFileSync(path.join(root,'app_production.html'),'utf8');
ok(!html.includes('part-crud-s2041.js?v=2041'),'S2041 must not be loaded standalone (bundled in S2041.1)');
ok(!prod.includes('part-crud-s2041.js?v=2041'),'production S2041 must not be loaded standalone');
ok(fs.readFileSync(path.join(root,'scripts/build.js'),'utf8').includes("'modules/vehicle/part-crud-s2041.js'"),'S2041 not registered in build.js');
ok(b.includes('PartCrudS2041'),'S2041 not present in app-bundle-b.min.js');
console.log('S2041 Part CRUD + PartPicker accumulation audit: PASS');
ok(ext.includes('pickerDefaults'),'context-specific picker defaults missing');
ok(ext.includes("selectId==='servisPartId'"),'service available default missing');
ok(ext.includes('includeUnclassified'),'strict category/component filter missing');
ok(ext.includes('vehicleIds'),'multi-vehicle compatibility filter missing');
ok(ext.includes('strictFilters:true'),'strict filter audit metadata missing');
console.log('S2041 strict filter + context defaults audit: PASS');

ok(ext.includes('txStockCategoryFilter') && ext.includes('txStockComponentFilter'),'transaction-local category/component filters missing');
ok(ext.includes("base.categoryId=txCategory()") && ext.includes("base.componentId=txComponent()"),'transaction picker is not bound to its local filters');
ok(ext.includes('nextHtml!==currentHtml'),'part dropdown DOM idempotency guard missing');
ok(ext.includes('refreshQueued'),'refresh coalescing guard missing');
ok(ext.includes('catHtml!==catCurrent') && ext.includes('compHtml!==compCurrent'),'transaction filter DOM idempotency guard missing');
ok(ext.includes("className='u-grid2 u-mt6'"),'transaction filters do not reuse existing compact grid utility');
console.log('S2041 transaction-local filter + UI regression guard audit: PASS');
