const assert=require('assert');const fs=require('fs');const vm=require('vm');
function load(opts={}){const store=opts.localStorage||{data:new Map(),getItem(k){return this.data.get(k)||null},setItem(k,v){this.data.set(k,String(v))},removeItem(k){this.data.delete(k)}};const ctx={console,localStorage:store,setTimeout:()=>{},IDBStore:opts.IDBStore||null,AIBus:opts.AIBus||{emit:()=>{}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('modules/finance/finance-event-outbox.js','utf8'),ctx);return {ctx,store};}
(async()=>{let pass=0,total=0;const t=async(n,f)=>{total++;try{await f();pass++;console.log('PASS',n)}catch(e){console.error('FAIL',n,e.stack||e)}};
await t('queue bound rejects new event without dropping oldest',()=>{const x=load();for(let i=0;i<100;i++)assert(x.ctx.FinanceEventOutbox.enqueue('e',{i}));assert.strictEqual(x.ctx.FinanceEventOutbox.enqueue('e',{i:100}),false);assert.strictEqual(x.ctx.FinanceEventOutbox.pending().length,100);assert.strictEqual(x.ctx.FinanceEventOutbox.pending()[0].payload.i,0)});
await t('legacy overflow is preserved, not truncated',()=>{const ls={data:new Map([['kw_finance_event_outbox_v1',JSON.stringify(Array.from({length:101},(_,i)=>({id:'e'+i,eventId:'e'+i,type:'e',payload:{i},seq:i+1})))]]),getItem(k){return this.data.get(k)||null},setItem(k,v){this.data.set(k,String(v))},removeItem(k){this.data.delete(k)}};const x=load({localStorage:ls});assert.strictEqual(x.ctx.FinanceEventOutbox.pending().length,101);assert.strictEqual(x.ctx.FinanceEventOutbox.pending()[0].payload.i,0)});
await t('duplicate ID is idempotent and does not consume capacity',()=>{const x=load();assert(x.ctx.FinanceEventOutbox.enqueue('e',{x:1}));const raw=JSON.parse(x.store.getItem('kw_finance_event_outbox_v1'));const item=raw[0];const again=JSON.stringify([item]);x.store.setItem('kw_finance_event_outbox_v1',again);const y=load({localStorage:x.store});assert(y.ctx.FinanceEventOutbox.enqueue('e',{x:2})||true);assert.strictEqual(y.ctx.FinanceEventOutbox.pending().length,2)});
await t('atomic staging refuses overflow instead of silently dropping events',()=>{const x=load();const ok=x.ctx.FinanceEventOutbox.stageBatch(Array.from({length:101},(_,i)=>['e',{i}]));assert.strictEqual(ok,false);assert.strictEqual(x.ctx.FinanceEventOutbox.pending().length,0)});
await t('failed replay keeps entire remaining queue',async()=>{let calls=0;const x=load({IDBStore:{get:async()=>null,set:async(k,v)=>{x.saved=v}} ,AIBus:{emit:()=>{},emitAsync:async()=>{calls++;throw Error('fail')}}});for(let i=0;i<3;i++)x.ctx.FinanceEventOutbox.enqueue('e',{i});const ok=await x.ctx.FinanceEventOutbox.replay();assert.strictEqual(ok,false);assert.strictEqual(x.ctx.FinanceEventOutbox.pending().length,3);assert.strictEqual(calls,1)});
console.log(`S2205 ${pass}/${total}`);if(pass!==total)process.exit(1);})();
