'use strict';
const test=require('node:test'); const assert=require('node:assert/strict'); const fs=require('node:fs');
const {loadSource}=require('./helpers/loadSource');
test('S2504-S2508 cumulative Finance taxonomy hardening — one gate',()=>{
 const D={categories:{income:[{id:'inc',name:'Gaji',subs:[]}],expense:[{id:'p',name:'Belanja',classification:'POKOK',subs:[{id:'sp',name:'Harian',classification:'POKOK'}]},{id:'w',name:'Transport',classification:'WAJIB',subs:[{id:'sw',name:'Servis',classification:'WAJIB'}]},{id:'b',name:'Bisnis',classification:'BISNIS',subs:[]}]},transactions:[],budgets:[{id:'b1',catIds:['p','sp']}]};
 const c=loadSource(['modules/finance/finance-category-sot.js','modules/finance/finance-tx-sot.js'],{D},['FinanceCategorySOT','FinanceTxSOT']); const S=c.FinanceCategorySOT,T=c.FinanceTxSOT;
 const tx=T.create({id:'t',type:'expense',category:'Belanja',subcategory:'Harian',amount:1}); assert.equal(tx.categoryId,'p'); assert.equal(tx.subcategoryId,'sp'); assert.equal(S.resolveSeven(tx),'POKOK');
 S.updateCategory('expense','p',{name:'Kebutuhan'}); S.updateSubcategory('expense','p','sp',{name:'Harian Baru'}); assert.equal(tx.category,'Kebutuhan'); assert.equal(tx.subcategory,'Harian Baru');
 assert.throws(()=>T.create({id:'bad',type:'expense',category:'NOPE',amount:1}),/FINANCE_CATEGORY_UNRESOLVED/);
 assert.throws(()=>T.create({id:'cross',type:'expense',categoryId:'b',category:'Bisnis',subcategoryId:'sw',subcategory:'Servis',amount:1}),/FINANCE_CATEGORY_UNRESOLVED/);
 const before=T.snapshot(); const rows=[{id:'batch-ok',type:'expense',category:'Bisnis',amount:2},{id:'batch-bad',type:'expense',category:'NOPE',amount:3}]; assert.throws(()=>T.createMany(rows),/FINANCE_CATEGORY_UNRESOLVED/); assert.deepEqual(T.snapshot(),before); assert.equal(rows[0].categoryId,undefined);
 assert.throws(()=>T.replaceSnapshot([{id:'restore-ok',type:'expense',category:'Bisnis',amount:2},{id:'restore-bad',type:'expense',category:'NOPE',amount:3}]),/FINANCE_CATEGORY_UNRESOLVED/); assert.deepEqual(T.snapshot(),before);
 D.categories.expense.push({id:'dup',name:'Bisnis',classification:'BISNIS',subs:[]}); T.create({id:'m',type:'expense',categoryId:'dup',category:'Bisnis',amount:4}); D.budgets[0].catIds.push('dup'); const m=S.mergeDuplicates('expense'); assert.equal(m.categoryRemap.dup,'b'); assert.equal(T.findById('m').categoryId,'b'); assert.ok(D.budgets[0].catIds.includes('b'));
 const seven=['POKOK','WAJIB','RUTIN','KEINGINAN','BISNIS','INVESTASI','SOSIAL']; assert.equal(S.resolveSeven({type:'income',category:'Gaji'}),null); assert.equal(S.resolveSeven({type:'expense',category:'Tidak Teridentifikasi'}),null); assert.equal(seven.length,7);
 const d=S.addCategory('expense',{id:'del',name:'Temporary',classification:'RUTIN'}); S.addSubcategory('expense','del',{id:'sdel',name:'Temp',classification:'RUTIN'}); T.create({id:'dt',type:'expense',categoryId:'del',subcategoryId:'sdel',category:'Temporary',subcategory:'Temp',amount:1}); D.budgets[0].catIds.push('del','sdel'); S.removeCategory('expense','del'); assert.equal(T.findById('dt').categoryId,undefined); assert.equal(D.budgets[0].catIds.includes('del'),false); assert.equal(D.budgets[0].catIds.includes('sdel'),false);
 const f=fs.readFileSync('modules/finance/filter-laporan.js','utf8'); assert.match(f,/fClass/); assert.match(f,/kfClass/); assert.match(f,/FinanceCategorySOT[\s\S]*resolveSeven/);
 for(const file of ['modules/vehicle/servis.js','modules/vehicle/servis-b.js','modules/vehicle/vehicle-core.js','modules/finance/transaksi-b.js','modules/finance/titipan-expense-flow.js','modules/finance/pajak-pbb-zakat.js','modules/home/renovasi.js','modules/asset/investasi.js','modules/shop/cobek-order.js','modules/shop/business-flow-presenter-inventory.js','modules/shop/cobek-etalase.js','modules/shared/modules-calc.js']){const s=fs.readFileSync(file,'utf8'); assert.doesNotMatch(s,/else\s+D\.transactions\.push\(/,file); assert.doesNotMatch(s,/else\s+D\.transactions\s*=\s*D\.transactions\.filter\(/,file);}
 const build=fs.readFileSync('scripts/build.js','utf8'); assert.ok(build.indexOf("'modules/finance/finance-category-sot.js'")<build.indexOf("'modules/finance/finance-tx-sot.js'"));
});
