const test=require('node:test'); const assert=require('node:assert/strict');
function fresh(){delete global.ServiceHistoryAuditPackage;global.D={servisLogs:[{id:'a',vehicleId:'v1',date:'2026-09-01',km:100,item:'Jasa',cost:100000,serviceJobType:'overhaul_turun_mesin',serviceJobLabel:'Overhaul / Turun Mesin'},{id:'b',vehicleId:'v1',date:'2026-09-02',km:120,item:'Part',cost:200000,serviceJobType:'overhaul_turun_mesin',serviceJobLabel:'Overhaul / Turun Mesin'},{id:'c',vehicleId:'v1',date:'2026-09-03',km:130,item:'Other',cost:50000}],serviceAuditGroups:[]};delete require.cache[require.resolve('../modules/vehicle/service-history-audit-package.js')];return require('../modules/vehicle/service-history-audit-package.js');}
test('S1980 package lifecycle create/read/update/delete preserves source rows',()=>{const api=fresh();global.save=()=>true;let r=api.create({vehicleId:'v1',title:'Overhaul',typeId:'overhaul_turun_mesin',sourceServiceIds:['a','b']});assert.equal(r.ok,true);const id=r.package.id;assert.equal(api.audit(id).summary.jobTypes[0].label,'Overhaul / Turun Mesin');assert.equal(api.audit(id).summary.dateMin,'2026-09-01');assert.equal(api.audit(id).summary.dateMax,'2026-09-02');r=api.update(id,{status:'done',title:'Overhaul selesai'});assert.equal(r.ok,true);assert.equal(api.byId(id).status,'done');r=api.remove(id);assert.equal(r.ok,true);assert.equal(global.D.servisLogs.length,3);});
test('S1980 duplicate source set is rejected',()=>{const api=fresh();global.save=()=>true;assert.equal(api.create({vehicleId:'v1',sourceServiceIds:['a','b']}).ok,true);const r=api.create({vehicleId:'v1',sourceServiceIds:['b','a']});assert.equal(r.code,'duplicate_source_package');});
test('S1980 >100 source records rejected at API',()=>{const api=fresh();global.D.servisLogs=Array.from({length:101},(_,i)=>({id:String(i),vehicleId:'v1'}));const r=api.create({vehicleId:'v1',sourceServiceIds:global.D.servisLogs.map(x=>x.id)});assert.equal(r.code,'too_many_source_records');});
test('S1980 create rolls back on persistence failure',()=>{const api=fresh();global.save=()=>false;const r=api.create({vehicleId:'v1',sourceServiceIds:['a','b']});assert.equal(r.code,'persistence_failed');assert.equal(global.D.serviceAuditGroups.length,0);});
test('S1980 update rolls back on persistence failure',()=>{const api=fresh();global.save=()=>true;const p=api.create({vehicleId:'v1',sourceServiceIds:['a','b']}).package;global.save=()=>false;const r=api.update(p.id,{title:'Changed',status:'done'});assert.equal(r.code,'persistence_failed');assert.equal(api.byId(p.id).title,'Paket Pekerjaan');assert.equal(api.byId(p.id).status,'active');});
test('S1980 remove rolls back on persistence failure',()=>{const api=fresh();global.save=()=>true;const p=api.create({vehicleId:'v1',sourceServiceIds:['a','b']}).package;global.save=()=>false;const r=api.remove(p.id);assert.equal(r.code,'persistence_failed');assert.ok(api.byId(p.id));});
test('S1980 package summary follows current source data',()=>{const api=fresh();global.save=()=>true;const p=api.create({vehicleId:'v1',sourceServiceIds:['a','b']}).package;global.D.servisLogs[0].cost=300000;const a=api.audit(p.id);assert.equal(a.summary.totalCost,500000);});
