'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const T=require('../modules/vehicle/service-condition-timeline-sot');
const C=require('../modules/vehicle/service-part-compatibility-sot');
const I=require('../modules/vehicle/service-event-idempotency-sot');
const R=require('../modules/vehicle/reminder-lifecycle');
const V=require('../modules/vehicle/vehicle-isolation-audit-sot');
const M=require('../modules/vehicle/maintenance-intelligence-v2-sot');
const G=require('../modules/vehicle/service-ingestion-provenance-sot');
const E=require('../modules/vehicle/service-evidence-pack-sot');
const Q=require('../modules/vehicle/service-roundtrip-sot');
const rows=[{id:'a',vehicleId:'v1',serviceComponentId:'c1',date:'2026-01-01',km:1000,conditionResult:'baik'},{id:'b',vehicleId:'v1',serviceComponentId:'c1',date:'2026-04-01',km:4000,conditionResult:'aus',idempotencyKey:'k'}];
test('S1910 timeline is ordered and descriptive',()=>{const x=T.summarize(rows,'v1','c1');assert.equal(x.count,2);assert.equal(x.observations[1].delta,2);assert.equal(x.observations[1].deltaKm,3000);});
test('S1911 explicit component-part compatibility only',()=>{const p=[{id:'p1',serviceComponentIds:['c1'],compatibleVehicleIds:['v1']}];assert.equal(C.resolve(p,'v1','c1','p1').ok,true);assert.equal(C.resolve(p,'v1','c1','p2').ok,false);});
test('S1912 deterministic idempotency and duplicate audit',()=>{const k=I.key({vehicleId:'v1',serviceComponentId:'c1',date:'2026-01-01'});assert.equal(k,'service:v1:c1:2026-01-01:default:');assert.equal(I.audit([{id:'1',vehicleId:'v1',idempotencyKey:'x'},{id:'2',vehicleId:'v1',idempotencyKey:'x'}]).ok,false);});
test('S1913 terminal reminder cannot reopen',()=>{assert.equal(R.transition('COMPLETED','ACTIVE').ok,false);assert.equal(R.transition('ACTIVE','COMPLETED').ok,true);});
test('S1914 vehicle isolation rejects orphan',()=>{assert.equal(V.audit({vehicles:[{id:'v1'}],servisLogs:[{id:'s',vehicleId:'v2'}]}).ok,false);});
test('S1915 intelligence remains descriptive',()=>{const x=M.analyze(rows,'v1','c1');assert.equal(x.count,2);assert.equal(x.rateKmPerEvent,3000);assert.equal(x.readOnly,true);});
test('S1916 ingestion is preview-first',()=>{const p=G.preview({date:'2026-09-01',item:'Ganti Oli'},{sourceType:'ocr',sourceRef:'scan-1'});assert.equal(p.ok,true);assert.equal(p.requiresConfirmation,true);assert.equal(G.toServiceEvent(p.candidate).ok,false);assert.equal(G.toServiceEvent(p.candidate,true).ok,true);});
test('S1917 evidence pack is deterministic read-only summary',()=>{const x=E.build({vehicles:[{id:'v1'}],servisLogs:rows,transactions:[],reminders:[]});assert.equal(x.counts.services,2);assert.equal(x.readOnly,true);});
test('S1920 round-trip preserves service domain identity',()=>{const x=Q.certify({vehicles:[{id:'v1'}],servisLogs:rows,transactions:[],partsStock:[],sparepartCats:[],serviceReminders:[]});assert.equal(x.ok,true);assert.equal(x.identityPreserved,true);});
