const test=require('node:test'); const assert=require('node:assert/strict');
function load(){global.window=global; global.D={servisLogs:[],transactions:[]}; delete require.cache[require.resolve('../modules/vehicle/service-event-sot.js')]; return require('../modules/vehicle/service-event-sot.js');}
test('S1946 unified event normalizes checklist/evidence/cost',()=>{const S=load();const x={id:'s1',vehicleId:'v1',date:'2026-01-01',km:1000,cost:50000,txLinkId:'t1',checklist:[{itemId:'c1',itemName:'X',actionType:'ganti'}],foto:['p']};const r=S.normalize(x,{persist:false});assert.equal(r.ok,true);assert.equal(x.checklist[0].state,'REPLACED');assert.equal(x.serviceEvidence.transactionId,'t1');assert.equal(x.costBreakdown.total,50000);});
test('S1947 overhaul never invents due interval',()=>{const S=load();const r=S.nextDue({serviceJobType:'overhaul_turun_mesin',nextDueKm:999});assert.equal(r.mode,'RECOMMENDED_REVIEW');assert.equal(r.nextDueKm,null);});
test('S1948 checklist state machine',()=>{const S=load();assert.equal(S.checklistState({conditionResult:'ok'}),'OK');assert.equal(S.checklistState({conditionResult:'needs_repair'}),'NEEDS_REPAIR');assert.equal(S.checklistState({conditionResult:'deferred'}),'DEFERRED');assert.equal(S.checklistState({notApplicable:true}),'NOT_APPLICABLE');});
test('S1950 cost breakdown preserves unknown components',()=>{const S=load();const r=S.normalizeCost({cost:123});assert.equal(r.total,123);assert.equal(r.labor,null);assert.equal(r.parts,null);});
test('S1951 evidence is provenance only',()=>{const S=load();const e=S.evidence({vehicleId:'v',sessionId:'s',catalogPartId:'p',foto:['a','b']});assert.deepEqual(e.photoRefs,['a','b']);assert.equal(e.catalogPartId,'p');});
test('S1952 health is vehicle scoped',()=>{const S=load();global.D.servisLogs=[{id:'1',vehicleId:'v1',date:'2026-01-01',checklist:[{itemId:'c1',itemName:'X',conditionResult:'ok'}]},{id:'2',vehicleId:'v2',date:'2026-01-01',checklist:[{itemId:'c2',itemName:'Y',conditionResult:'needs_repair'}]}];const r=S.maintenanceHealth('v1');assert.equal(r.components.length,1);assert.equal(r.components[0].name,'X');});
test('S1953 audit detects orphan finance link',()=>{const S=load();global.D.servisLogs=[{id:'s',vehicleId:'v',txLinkId:'missing',checklist:[]}];const r=S.audit('v');assert.ok(r.issues.some(x=>x.code==='ORPHAN_TRANSACTION'));});
