const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const s=fs.readFileSync(path.join(__dirname,'../modules/vehicle/servis.js'),'utf8');
const audit=fs.readFileSync(path.join(__dirname,'../modules/vehicle/service-history-bulk-identity-editor.js'),'utf8');
test('S1974 history is read-only while reminder remains a separate presenter and audit package stays available',()=>{
 const start=s.indexOf('renderEditHistoryTab(){'); const end=s.indexOf('createHistoryAuditPackage(){',start); const history=s.slice(start,end);
 assert.doesNotMatch(history,/renderEditCanonicalSelectors/);
 assert.doesNotMatch(history,/computeServiceUrgency/);
 assert.doesNotMatch(history,/Reminder aktif/);
 assert.match(history,/Halaman ini hanya menampilkan bukti riwayat/);
 assert.match(s,/renderEditReminderTab\(\)/);
 assert.match(s,/setEditTab\(tab\)/);
 assert.match(s,/tab==='audit'\?'audit'/);
 assert.match(audit,/renderEditAuditTab/);
 assert.match(s,/createHistoryAuditPackage/);
 assert.match(s,/sourceServiceIds:ids/);
 assert.match(s,/openHistoryAuditPackage/);
 assert.match(s,/openHistorySourceFromAudit/);
 assert.match(audit,/Jadikan Paket Pekerjaan/);
});
console.log('S1961 history reminder/package coexistence: PASS');
