const fs=require('fs');
const assert=require('assert');
const js=fs.readFileSync(require('path').join(__dirname,'..','car-notes.js'),'utf8');
assert(js.includes('linkedReminderInfo'),'3F reminder linkage UI missing');
assert(js.includes('getEffectiveIntervalKm(curVehicleId,linkedCat)'),'3F must reuse effective KM interval');
assert(js.includes('getEffectiveIntervalBulan(curVehicleId,linkedCat)'),'3F must reuse effective month interval');
assert(js.includes('resolveServisCatForVehicle(s.item,curVehicleId)'),'3F legacy fallback missing');
assert(js.includes('Pengingat belum aktif'),'3F inactive reminder state missing');
assert(js.includes('Terhubung ke Pengingat Servis'),'3F linked tooltip missing');
const css=fs.readFileSync(require('path').join(__dirname,'..','styles.css'),'utf8');
assert(css.includes('.servis-history-reminder'),'3F CSS missing');
console.log('Sesi 3F: 7/7 PASS');
