'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const src=fs.readFileSync('modules/vehicle/service-category-component-history-audit-s2034.js','utf8');
function api(extra={}){const c={console,Date,JSON,Math,Number,String,Array,Object,Map,Set,Promise,...extra};vm.createContext(c);vm.runInContext(src,c);return c.ServiceCategoryComponentHistoryAuditS2034;}
function cat(){return {itemById(id){if(id==='coolant')return {item:{id:'coolant',name:'Coolant',masterCategoryId:'cooling',intervalKm:4000,intervalTimeMonths:24},group:{masterCategoryId:'cooling',group:'Sistem Pendingin'}};return null},infer(n){return String(n).trim().toLowerCase()==='coolant'?this.itemById('coolant'):null}};}
test('S2034 category identity + interval override audit',()=>{const A=api({ServiceInputCatalog:cat()});const r=A.auditCategory({id:'c1',vehicleId:'v1',name:'Cairan pendingin radiator (coolant)',masterCategoryId:'wrong',serviceComponentId:'coolant',intervalKm:5000,intervalBulan:24});assert.equal(r.ok,false);assert.ok(r.issues.some(x=>x.code==='component-name-drift'));assert.ok(r.issues.some(x=>x.code==='master-category-drift'));assert.ok(r.issues.some(x=>x.code==='interval-km-override'));});
test('S2034 duplicate canonical category projection is detected per vehicle',()=>{const A=api({ServiceInputCatalog:cat()});const r=A.auditCategories([{id:'a',vehicleId:'v1',name:'Coolant',masterCategoryId:'cooling',serviceComponentId:'coolant'},{id:'b',vehicleId:'v1',name:'Coolant',masterCategoryId:'cooling',serviceComponentId:'coolant'}],'v1');assert.equal(r.duplicates.length,1);assert.equal(Array.from(r.duplicates[0].categoryIds).join(','),'a,b');});
test('S2034 existing history audit is read-only and preserves historical snapshot differences',()=>{const A=api({ServiceInputCatalog:cat()});const log={id:'h1',vehicleId:'v1',categoryId:'c1',serviceComponentId:'coolant',masterCategoryId:'cooling',serviceComponentNameSnapshot:'Cairan pendingin radiator (coolant)',item:'Cairan pendingin radiator (coolant)',intervalKmAtService:4000,intervalBulanAtService:12};const cats=[{id:'c1',vehicleId:'v1',name:'Coolant',masterCategoryId:'cooling',serviceComponentId:'coolant',intervalKm:5000,intervalBulan:24}];const before=JSON.stringify(log),r=A.auditHistory(log,cats);assert.equal(JSON.stringify(log),before);assert.ok(r.issues.some(x=>x.code==='historical-name-snapshot-differs'));assert.ok(r.issues.some(x=>x.code==='historical-interval-differs'));});
test('S2034 history category/component drift is ERROR',()=>{const A=api({ServiceInputCatalog:cat()});const r=A.auditHistory({id:'h2',vehicleId:'v1',categoryId:'wrong',serviceComponentId:'coolant',masterCategoryId:'cooling',item:'Coolant'},[{id:'wrong',vehicleId:'v1',name:'Oli Mesin',masterCategoryId:'engine',serviceComponentId:'oil'}]);assert.equal(r.ok,false);assert.ok(r.issues.some(x=>x.code==='history-category-component-drift'));});
test('S2034 save path canonicalizes category name from resolved component',()=>{const src=fs.readFileSync('modules/vehicle/sparepart-servis-ui.js','utf8');assert.ok(src.includes('if(linkage.componentName) name=String(linkage.componentName).trim();'));assert.ok(src.includes('syncCategoryComponentIdentity(){'));});
test('S2034 build wiring + modal selectors',()=>{const b=fs.readFileSync('scripts/build.js','utf8');assert.ok(b.indexOf('service-category-component-history-audit-s2034.js')<b.indexOf("'modules/vehicle/sparepart-servis.js'"));const m=fs.readFileSync('modules/shared/modals.js','utf8');assert.ok(m.includes('sparepartMasterCategoryId'));assert.ok(m.includes('sparepartServiceComponentId'));assert.ok(m.includes('Sparepart.syncCategoryServiceComponent()'));assert.ok(m.includes('Sparepart.syncCategoryComponentIdentity()'));});
