const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const car=fs.readFileSync(path.join(root,'car-notes.js'),'utf8');
const bundle=fs.readFileSync(path.join(root,'app-bundle-a.min.js'),'utf8');
const checklist=fs.readFileSync(path.join(root,'modules/vehicle/servis-checklist.js'),'utf8');
let pass=0;
function ok(c,m){if(!c)throw new Error(m);pass++;console.log('PASS',m);}
const ids=[...checklist.matchAll(/\bid:\s*['"]([^'"]+)['"]/g)].map(m=>m[1]);
const registry=car.match(/const SERVICE_MAINTENANCE_RULES\s*=\s*Object\.freeze\(\{([\s\S]*?)\}\);/);
ok(!!registry,'maintenance registry exists');
ok(ids.length===30,'KZR checklist contains 30 components');
const rules=[...registry[1].matchAll(/^\s*['"]([^'"]+)['"]\s*:\s*\{/gm)].map(m=>m[1]);
ok(rules.length===30,'maintenance registry contains 30 rules');
ok(new Set(rules).size===rules.length,'maintenance rule IDs are unique');
for(const id of ids)ok(rules.includes(id),'rule covers '+id);
for(const id of rules)ok(ids.includes(id),'no orphan rule '+id);
ok(car.includes('function validateMaintenanceRuleRegistry'),'validator exists in source');
ok(bundle.includes('function validateMaintenanceRuleRegistry'),'validator exists in bundle A');
ok(/window\.validateMaintenanceRuleRegistry/.test(car),'validator exposed globally');
ok(/1676/.test(fs.readFileSync(path.join(root,'sw.js'),'utf8')),'cache version bumped to v1676');
console.log(`${pass} PASS`);
