'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..');
const source=fs.readFileSync(path.join(root,'modules/vehicle/service-history-reminder-component-s2026.js'),'utf8');
const logs=[{id:'h1',vehicleId:'v1',sessionId:'s1',item:'Servis Rutin',checklist:[{itemId:'belt',itemName:'V-Belt CVT',serviceComponentId:'belt',actionType:'ganti'},{itemId:'roller',itemName:'Roller CVT',serviceComponentId:'roller'}]}];
const context={console,D:{servisLogs:logs},Servis:{editId:'h1',_s2019ComponentFocusId:'belt',_s2019ComponentFocusLogId:'h1',renderEditReminderTab(){}},ServiceHistoryMultiChecklistS2019:{componentsOf(log){return (log.checklist||[]).map(x=>({...x,componentName:x.itemName,key:x.itemId,checklistItemId:x.itemId}));}},escapeHtml:x=>String(x==null?'':x),window:null,document:{addEventListener(){},getElementById(){return null;}}};context.window=context;vm.createContext(context);vm.runInContext(source,context,{filename:'service-history-reminder-component-s2026.js'});
const api=context.ServiceHistoryReminderComponentS2026;
assert.ok(api);
const before=JSON.stringify(logs);
const r=api.audit(logs[0],'belt');
assert.equal(r.status,'OK');assert.equal(r.componentId,'belt');assert.equal(r.readOnly,true);
const p=api.projection(logs[0],r.component);assert.equal(p.item,'V-Belt CVT');assert.equal(p.serviceComponentId,'belt');
assert.equal(JSON.stringify(logs),before,'S2026 must remain read-only');
context.Servis._s2019ComponentFocusId='missing';
assert.equal(api.audit(logs[0],'belt').status,'WARNING');
assert.equal(api.audit(logs[0],'missing').status,'ERROR');
context.Servis._s2019ComponentFocusId='belt';
const html=api.render(logs[0],'belt');assert.match(html,/Reminder/);assert.match(html,/component scope/);assert.match(html,/V-Belt CVT/);
const s2019=fs.readFileSync(path.join(root,'modules/vehicle/service-history-multichecklist-s2019.js'),'utf8');assert.match(s2019,/reminderProjection:reminderProxy/);
console.log('S2026 component-scoped reminder UX regression: PASS');
