const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const car=fs.readFileSync(path.join(root,'car-notes.js'),'utf8');
const spare=fs.readFileSync(path.join(root,'modules/vehicle/sparepart-servis.js'),'utf8');
const a=fs.readFileSync(path.join(root,'app-bundle-a.min.js'),'utf8');
const b=fs.readFileSync(path.join(root,'app-bundle-b.min.js'),'utf8');
let pass=0;
function ok(cond,msg){if(!cond)throw new Error(msg);pass++;console.log('PASS',msg);}
ok(car.includes('function getMaintenanceReminderProjection(vehicleId)'), 'source has maintenance reminder projection');
ok(car.includes('function getReminderCategoriesForVehicle(vehicleId)'), 'source has reminder category pool');
ok(car.includes('resolveReminderCategory(catId,curVehicleId)'), 'markServiced resolves projected category');
ok(car.includes('const reminderCategoryPool='), 'Reminder consumes projected category pool');
ok(spare.includes('s.inspectDays||s.replaceDays'), 'day-axis schedules are considered remindable');
ok(a.includes('function getMaintenanceReminderProjection(vehicleId)'), 'bundle A contains projection');
ok(a.includes('const reminderCategoryPool='), 'bundle A contains projection pool in Reminder');
ok(b.includes('s.inspectDays||s.replaceDays'), 'bundle B contains day-axis remindable check');
const indexSrc=fs.readFileSync(path.join(root,'index.html'),'utf8');
const productionSrc=fs.readFileSync(path.join(root,'app_production.html'),'utf8');
const swSrc=fs.readFileSync(path.join(root,'sw.js'),'utf8');
const version=(indexSrc.match(/app-bundle-a\.min\.js\?v=(\d+)/)||[])[1];
ok(!!version,'index contains a numeric cache-bust version');
ok(new RegExp('app-bundle-a\\.min\\.js\\?v='+version).test(indexSrc),'index bundle A uses current cache version');
ok(new RegExp('app-bundle-a\\.min\\.js\\?v='+version).test(productionSrc),'production bundle A uses current cache version');
ok(swSrc.includes('kw-cache-v'+version),'service-worker cache uses current numeric version');
console.log(`${pass}/11 PASS`);
