'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const ROOT=path.join(__dirname,'..');
function load(extra={}){const ctx={console,Date,Math,JSON,Number,String,Boolean,Array,Object,Map,Set,Promise,globalThis:null,...extra};ctx.globalThis=ctx;vm.createContext(ctx);for(const f of ['modules/vehicle/service-master-data.generated.js','modules/vehicle/service-master-database.js','modules/vehicle/service-maintenance-engine.js'])vm.runInContext(fs.readFileSync(path.join(ROOT,f),'utf8'),ctx,{filename:f});return ctx;}
function fakeIDB(){let store=null,writes=0,reads=0;return{IDBStore:{async get(){reads++;return store;},async set(k,v){writes++;store=JSON.parse(JSON.stringify(v));return true;}},stats:()=>({reads,writes,store})};}
test('master JSON generated artifact preserves 13 categories / 102 cumulative components and stable legacy IDs',()=>{const d=require('../modules/vehicle/service-master-data.generated.js').SERVICE_MASTER_DATA;assert.equal(d.masterCategoryCount,13);assert.equal(d.componentCount,102);assert.equal(new Set(d.masterCategories.map(x=>x.masterCategoryId)).size,13);assert.equal(new Set(d.components.map(x=>x.componentId)).size,102);});
test('ServiceMasterDB first install seeds existing IDBStore key and is idempotent on second load',async()=>{const f=fakeIDB();const c=load(f);const a=await c.ServiceMasterDB.ensureLoaded();assert.equal(a.categories.length,13);assert.equal(a.components.length,102);assert.equal(f.stats().writes,1);await c.ServiceMasterDB.ensureLoaded();assert.equal(f.stats().writes,1);});
test('ServiceMasterDB import update does not duplicate componentId and removed master stays deprecated',async()=>{const f=fakeIDB();const c=load(f);await c.ServiceMasterDB.ensureLoaded();const d=JSON.parse(JSON.stringify(c.__SERVICE_MASTER_DATA__));d.components=d.components.map(x=>x.componentId==='oli-mesin'?{...x,componentName:'Oli Mesin UPDATED'}:x).filter(x=>x.componentId!=='filter-oli');await c.ServiceMasterDB.importMasterData(d);const s=c.ServiceMasterDB.getStore();assert.equal(s.components.filter(x=>x.componentId==='oli-mesin').length,1);assert.equal(s.components.find(x=>x.componentId==='oli-mesin').componentName,'Oli Mesin UPDATED');assert.equal(s.components.find(x=>x.componentId==='filter-oli').deprecated,true);});
test('health engine: km threshold exact is DUE and beyond threshold is OVERDUE',async()=>{const c=load({D:{servisLogs:[]}});const component=c.__SERVICE_MASTER_DATA__.components.find(x=>x.componentId==='oli-mesin');const vehicle={id:'v1',currentOdometer:8000};const last={vehicleId:'v1',serviceComponentId:'oli-mesin',date:'2026-01-01',km:4000};let r=await c.ServiceMaintenanceEngine.evaluateComponentHealth({component,vehicle,latestMaintenance:last,currentDate:'2026-09-20'});assert.equal(r.status,'DUE');assert.equal(r.trigger,'km');vehicle.currentOdometer=8001;r=await c.ServiceMaintenanceEngine.evaluateComponentHealth({component,vehicle,latestMaintenance:last,currentDate:'2026-09-20'});assert.equal(r.status,'OVERDUE');});
test('health engine: both uses OR semantics; time can trigger while km remains below threshold',async()=>{const c=load({D:{servisLogs:[]}});const component=c.__SERVICE_MASTER_DATA__.components.find(x=>x.componentId==='minyak-rem');const r=await c.ServiceMaintenanceEngine.evaluateComponentHealth({component,vehicle:{id:'v1',currentOdometer:5000},latestMaintenance:{vehicleId:'v1',serviceComponentId:'minyak-rem',date:'2024-08-20',km:4000},currentDate:'2026-09-20'});assert.equal(r.status,'OVERDUE');assert.equal(r.trigger,'time');assert.equal(r.km.triggered,false);});
test('health engine: calendar month handling clamps Jan 31 + 1 month to Feb 28',()=>{const c=load();assert.equal(c.ServiceMaintenanceEngine.calendarMonths('2026-01-31','2026-02-27'),0);assert.equal(c.ServiceMaintenanceEngine.calendarMonths('2026-01-31','2026-02-28'),1);assert.equal(c.ServiceMaintenanceEngine.addMonthsClamped('2026-01-31',1).toISOString().slice(0,10),'2026-02-28');});
test('health engine: odometer regression is INSUFFICIENT_DATA, not negative due',async()=>{const c=load({D:{servisLogs:[]}});const component=c.__SERVICE_MASTER_DATA__.components.find(x=>x.componentId==='oli-mesin');const r=await c.ServiceMaintenanceEngine.evaluateComponentHealth({component,vehicle:{id:'v1',currentOdometer:3000},latestMaintenance:{vehicleId:'v1',serviceComponentId:'oli-mesin',date:'2026-01-01',km:4000},currentDate:'2026-09-20'});assert.equal(r.status,'INSUFFICIENT_DATA');assert.equal(r.km.reason,'odometer-regression');});
test('health engine: no history is explicit NO_HISTORY',async()=>{const c=load({D:{servisLogs:[]}});const component=c.__SERVICE_MASTER_DATA__.components.find(x=>x.componentId==='oli-mesin');const r=await c.ServiceMaintenanceEngine.evaluateComponentHealth({component,vehicle:{id:'v1',currentOdometer:5000},currentDate:'2026-09-20'});assert.equal(r.status,'NO_HISTORY');});
