const test=require('node:test'); const assert=require('node:assert/strict'); const {loadSource}=require('./helpers/loadSource');
function ctx(D){return loadSource(['modules/shop/shop-inventory-ledger.js','modules/shop/generic/product-repository.js','modules/shop/shop-sot-governance.js'],{D,save(){}},['ShopInventoryLedger','ProductRepository','ShopSotGovernance']);}
test('S1932 opening balance cutover creates explicit evidence without rewriting stock',()=>{const D={products:[{id:'p',stock:7}],shopInventoryLedger:[]};const c=ctx(D);const r=c.ShopSotGovernance.establishOpeningBalance('p',{stock:7,unitCost:100});assert.equal(r.ok,true);assert.equal(D.products[0].stock,7);assert.equal(D.shopInventoryLedger[0].source,'opening-balance');assert.equal(c.ShopInventoryLedger.reconcileProduct('p',D.products[0]).status,'PASS');});
test('S1933 receiving rejects over-receive and is idempotent',()=>{const D={products:[{id:'p',stock:0,hargaBeli:10}],purchaseOrders:[{id:'po',productId:'p',qty:2,status:'ORDERED',receivedQty:0,orderedUnitCost:10}],transactions:[],accounts:[{id:'a'}],shopInventoryLedger:[]};const c=loadSource(['modules/shop/shop-inventory-ledger.js','modules/shop/generic/product-repository.js','modules/shop/business-flow-presenter-inventory.js','modules/shop/shop-sot-governance.js'],{D,save(){},toast(){}},['ShopInventoryLedger','ProductRepository','BusinessFlowPresenterInventoryMixin','ShopSotGovernance']);const a=c.ShopSotGovernance.receivePurchase('po',3);assert.equal(a.ok,false);const b=c.ShopSotGovernance.receivePurchase('po',2);assert.equal(b.ok,true);const d=c.ShopSotGovernance.receivePurchase('po',2);assert.equal(d.alreadyReceived,true);assert.equal(D.products[0].stock,2);});
test('S1934 return posts stock and COGS reversal once',()=>{const D={products:[{id:'p',stock:3}],cobek:[{id:'s',items:[{productId:'p',qty:2,unitCost:10,cogs:20}],totalCogs:20}],shopReturns:[],shopInventoryLedger:[]};const c=ctx(D);const r=c.ShopSotGovernance.returnSale('s',{reason:'barang kembali'});assert.equal(r.ok,true);assert.equal(D.products[0].stock,5);assert.equal(r.return.totalCogsReversal,20);assert.equal(c.ShopSotGovernance.returnSale('s').duplicate,true);});
test('S1935 cost policy explicit and COGS uses stored snapshot',()=>{const D={shopCostPolicy:null,shopInventoryLedger:[]};const c=ctx(D);assert.equal(c.ShopSotGovernance.setCostPolicy('SNAPSHOT').ok,true);const r=c.ShopSotGovernance.cogsForSale({items:[{qty:2,unitCost:70,cogs:140}]});assert.equal(r.method,'SNAPSHOT');assert.equal(r.totalCogs,140);});
test('S1936 adjustment requires reason and leaves ledger evidence',()=>{const D={products:[{id:'p',stock:5}],shopInventoryLedger:[],shopStockAdjustments:[]};const c=ctx(D);assert.equal(c.ShopSotGovernance.adjustStock('p',-1,{reason:''}).ok,false);const r=c.ShopSotGovernance.adjustStock('p',-1,{reason:'rusak',type:'DAMAGE'});assert.equal(r.ok,true);assert.equal(D.products[0].stock,4);assert.equal(D.shopInventoryLedger.length,1);});
test('S1937 opname applies physical difference through adjustment gate',()=>{const D={products:[{id:'p',stock:5}],shopInventoryLedger:[],shopStockOpnames:[]};const c=ctx(D);const o=c.ShopSotGovernance.startOpname();c.ShopSotGovernance.countOpname(o.opname.id,'p',7);const r=c.ShopSotGovernance.approveOpname(o.opname.id);assert.equal(r.ok,true);assert.equal(D.products[0].stock,7);assert.equal(r.opname.status,'APPROVED');});
test('S1938 finance reconciliation only accepts explicit Shop links',()=>{const D={cobek:[{id:'s'}],purchaseOrders:[{id:'po'}],transactions:[{id:'t',cobekLinkId:'s'}],shopInventoryLedger:[]};const c=ctx(D);const r=c.ShopSotGovernance.reconcileFinance();assert.deepEqual(r.unlinkedSales,[]);assert.deepEqual(r.unlinkedPurchases,['po']);assert.equal(r.status,'GAP');});
test('S1939 certification distinguishes partial legacy evidence from verified',()=>{const D={products:[{id:'p',stock:2}],cobek:[{id:'s',items:[{productId:'p',qty:1,unitCost:10,cogs:10}]}],purchaseOrders:[],transactions:[],shopInventoryLedger:[]};const c=ctx(D);const r=c.ShopSotGovernance.certify();assert.equal(r.status,'PARTIALLY_VERIFIED');assert.equal(r.cutoverRequired,true);});
test('S1940 dashboard is read-only evidence model',()=>{const D={products:[],cobek:[],purchaseOrders:[],transactions:[],shopInventoryLedger:[],shopAuditTrail:[]};const c=ctx(D);const r=c.ShopSotGovernance.dashboard();assert.equal(r.title,'Shop Professional SOT');assert.equal(r.reconciliation.stock,'PASS');assert.equal(D.shopAuditTrail.length,0);});
