const test=require('node:test'); const assert=require('node:assert/strict'); const S=require('../modules/vehicle/vehicle-catalog-migration-sot.js');
const catalog=[
 {id:'c1',partName:'Filter Oli',oemCode:'15410-KZR-600',category:'Mesin',compatibleVehicleIds:['veh_1']},
 {id:'c2',partName:'Filter Oli',oemCode:'15410-ABC-999',category:'Mesin',compatibleVehicleIds:['veh_1']},
 {id:'c3',partName:'Busi',oemCode:'98056-54717',category:'Mesin',compatibleVehicleIds:['veh_1']},
 {id:'c4',partName:'Filter Oli',oemCode:'15410-KZR-600',category:'Mesin',compatibleVehicleIds:['veh_2']}
];
test('deterministic OEM match and cross-vehicle guard',()=>{let r=S.resolve({oemCode:'15410KZR600',vehicleId:'veh_1'},catalog,'veh_1');assert.equal(r.status,'linked');assert.equal(r.item.id,'c1');r=S.resolve({oemCode:'15410KZR600'},catalog,'veh_2');assert.equal(r.status,'linked');assert.equal(r.item.id,'c4');});
test('ambiguous identity never guesses',()=>{const c=catalog.concat({id:'c5',partName:'Busi',oemCode:'98056-54717',compatibleVehicleIds:['veh_1']});const r=S.resolve({oemCode:'9805654717'},c,'veh_1');assert.equal(r.status,'ambiguous');});
test('legacy transaction/service stock link is deterministic',()=>{const stock=[{id:'st1',name:'Filter Oli',catalogPartId:'c1'}];const tx={partStockId:'st1',name:'nama lama',amount:100};const r=S.resolve(tx,catalog,'veh_1',new Map([['st1',stock[0]]]));assert.equal(r.status,'linked');assert.equal(r.method,'legacy-stock-link');assert.equal(r.item.id,'c1');});
test('unique name+category is only a weak final deterministic signal',()=>{let r=S.resolve({name:'Busi',category:'Mesin'},catalog,'veh_1');assert.equal(r.status,'linked');assert.equal(r.method,'unique-name-category');const c=catalog.concat({id:'c6',partName:'Busi',category:'Mesin',compatibleVehicleIds:['veh_1']});r=S.resolve({name:'Busi',category:'Mesin'},c,'veh_1');assert.equal(r.status,'ambiguous');});
test('apply only adds identity metadata and preserves history fields',async()=>{const rows=[{id:'tx1',partStockId:'st1',name:'Nama Historis',date:'2020-01-01',amount:500,partStockQty:2}];const stock=[{id:'st1',name:'Filter Oli',catalogPartId:'c1'}];const before=JSON.stringify(rows);const r=await S.apply({catalogItems:catalog,partsStock:stock,transactions:rows,noSave:true,vehicleId:'veh_1'});assert.equal(r.applied,1);assert.equal(rows[0].catalogPartId,'c1');assert.equal(rows[0].name,'Nama Historis');assert.equal(rows[0].date,'2020-01-01');assert.equal(rows[0].amount,500);assert.notEqual(JSON.stringify(rows),before);});
test('dry-run reports ambiguous/unlinked without mutating',async()=>{const rows=[{id:'x',name:'Tidak Ada'}];const r=await S.dryRun({catalogItems:catalog,transactions:rows,vehicleId:'veh_1'});assert.equal(r.summary.unlinked,1);assert.equal(rows[0].catalogPartId,undefined);});
