const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const root=require('node:path').join(__dirname,'..');
function load(file){const src=fs.readFileSync(require('node:path').join(root,'modules/vehicle',file),'utf8');const c={console};vm.createContext(c);vm.runInContext(src,c);return c;}
test('SOT-3J blocks strong identity mutation when referenced',()=>{const a=load('vehicle-catalog-identity-sot.js').VehicleCatalogIdentitySOT;const r=a.guard('p1',{oemCode:'NEW'}, {oemCode:'OLD',barcode:'x'}, {partsStock:[{catalogPartId:'p1'}]});assert.equal(r.ok,false);assert.equal(r.referenced,true);});
test('SOT-3J allows identity mutation when unreferenced',()=>{const a=load('vehicle-catalog-identity-sot.js').VehicleCatalogIdentitySOT;assert.equal(a.guard('p1',{oemCode:'NEW'},{oemCode:'OLD'},{partsStock:[]}).ok,true);});
test('SOT-3J leaves service interval updates allowed',()=>{const a=load('vehicle-catalog-identity-sot.js').VehicleCatalogIdentitySOT;assert.equal(a.guard('p1',{serviceIntervalKm:5000},{oemCode:'OLD'},{transactions:[{catalogPartId:'p1'}]}).ok,true);});
test('SOT-3L certification source scans all domains and is read-only',()=>{const s=fs.readFileSync(require('node:path').join(root,'modules/vehicle/vehicle-catalog-certification-sot.js'),'utf8');assert.match(s,/partsStock/);assert.match(s,/transactions/);assert.match(s,/servisLogs/);assert.match(s,/carNotes/);assert.match(s,/readOnly:true/);assert.doesNotMatch(s,/VehicleCatalog\.update\(/);assert.doesNotMatch(s,/VehicleCatalog\.remove\(/);});
test('user-facing catalog import has no direct create fallback',()=>{const s=fs.readFileSync(require('node:path').join(root,'modules/vehicle/vehicle-catalog-import.js'),'utf8');assert.doesNotMatch(s,/VehicleCatalog\.create\(data\)/);assert.match(s,/VehicleCatalogWriteSOT\.ensurePart/);});
test('catalog UI has no direct create fallback',()=>{const s=fs.readFileSync(require('node:path').join(root,'modules/vehicle/vehicle-catalog-ui.js'),'utf8');assert.doesNotMatch(s,/res = await VehicleCatalog\.create\(data\)/);assert.match(s,/VehicleCatalogWriteSOT\.ensurePart/);});
test('final build loads migration, identity, certification after catalog',()=>{const b=fs.readFileSync(require('node:path').join(root,'scripts/build.js'),'utf8');const c=b.indexOf("'modules/vehicle/vehicle-catalog.js'");const m=b.indexOf("'modules/vehicle/vehicle-catalog-migration-sot.js'");const i=b.indexOf("'modules/vehicle/vehicle-catalog-identity-sot.js'");const f=b.indexOf("'modules/vehicle/vehicle-catalog-certification-sot.js'");assert.ok(c>=0&&m>c&&i>m&&f>i);});
test('legacy migration rules remain no-guess and no-create',()=>{const s=fs.readFileSync(require('node:path').join(root,'modules/vehicle/vehicle-catalog-migration-sot.js'),'utf8');assert.match(s,/ambiguousNoGuess:true/);assert.match(s,/createCatalog:false/);});
